// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'welcome',
    {
      type: 'category',
      label: 'Start Here — Maps of Content',
      collapsed: false,
      items: [
        'mocs/philosophy-map',
        'mocs/productivity-map',
        'mocs/pkm-map',
        'mocs/habits-map',
        'mocs/behavioral-psychology-map',
        'mocs/decision-making-map',
        'mocs/learning-map',
        'mocs/creativity-map',
        'mocs/obsidian-map',
        'mocs/data-analysis-map',
      ],
    },
    {
      type: 'category',
      label: 'All Maps of Content',
      link: { type: 'generated-index', description: 'Topic maps — each one gathers all notes on a given subject.' },
      items: [{ type: 'autogenerated', dirName: 'mocs' }],
    },
    {
      type: 'category',
      label: 'Atomic Notes',
      link: { type: 'generated-index', description: 'Individual idea notes — small, self-contained claims and concepts.' },
      items: [{ type: 'autogenerated', dirName: 'notes' }],
    },
    {
      type: 'category',
      label: 'Book Summaries',
      link: { type: 'generated-index', description: 'Key takeaways from non-fiction books.' },
      items: [{ type: 'autogenerated', dirName: 'books' }],
    },
  ],
};

export default sidebars;
